# Data situation is as follows:
# we have folders:
"""
data/images/0000_0.jpg (8376 images with 640x640x3 size)
data/saliency/0000_0.jpg (8376 images with 640x640x3 size)
data/crops.../0000_0_0.jpg

Where we have 3 sets of numbers delineated by underscore.

first 0000 - corresponds to unique route segments, they all have same score and shouldn't be in the same training and validation set
second _0 - corresponds to various positioning on the street, where we "stood" and "looked"
third _0 - this applies for crops, we generated k smaller crops

1 image <=> 1 saliency generated by [1] <=> k crops
(ps: k was initially 3)

[1] = https://github.com/imatge-upc/saliency-salgan-2017/

"""

import numpy as np
import os

def split_one_array(arr,validation_split=0.2):
    split_at = int(len(arr) * (1 - validation_split))
    arr_train = arr[0:split_at]
    arr_val = arr[split_at:]
    return arr_train,arr_val

def load_dictionaries(include_osm=False):
    filename = "id_to_score.npy"
    if include_osm:
        filename = "id_to_score_and_osm.npy"
    dictionary = np.load(filename).item()
    return dictionary

def get_data_from_folder(folder, include_osm=False):
    # get array of [[path,score,(osm)], ...]
    data = []
    dictionary = load_dictionaries(include_osm)

    files = os.listdir(folder)
    files.sort()
    for i in range(len(files)):
    #for i in range(5):
        file = files[i]
        if file.endswith(".jpg"):
            path = os.path.join(folder, file)
            underscores = file.split("_")
            id = -1
            if len(underscores) == 2:
                id = file[0:-4]
            elif len(underscores) == 3:
                id = underscores[0]+"_"+underscores[1]
            label = dictionary[id]

            data.append( [path] + label )
    return data

def default_load(folder="crops_50proc_3clusters"):
    data = get_data_from_folder(folder)

    data_train, data_val = split_one_array(data)

    #datat = np.transpose(data)
    #filenames = datat[0]
    #scores = datat[1]

    return data_train, data_val


a,b = default_load()
print a[0:2]
print b[0:2]